[Snyk] Fix for 1 vulnerabilities
equinor/videx-wellog pull request #234
Opened 2024-03-11 18:15 UTC by nadia-reinertsen

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to fix one or more vulnerable packages in the `npm` dependencies of this project.</h3>

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - examples/storybook/package.json
    - examples/storybook/package-lock.json

#### Vulnerabilities that will be fixed
##### With an upgrade:
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity")  |  **141/1000**  <br/> **Why?** Confidentiality impact: None, Integrity impact: None, Availability impact: High, Scope: Unchanged, Exploit Maturity: Proof of Concept, User Interaction (UI): None, Privileges Required (PR): None, Attack Complexity: Low, Attack Vector: Local, EPSS: 0.01055, Social Trends: No, Days since published: 102, Reachable: No, Transitive dependency: Yes, Is Malicious: No, Business Criticality: High, Provider Urgency: Medium, Package Popularity Score: 99, Impact: 5.99, Likelihood: 2.35, Score Version: V5  | Missing Release of Resource after Effective Lifetime <br/>[SNYK-JS-INFLIGHT-6095116](https://snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) |  Yes  | Proof of Concept 

(*) Note that the real score may have changed since the PR was raised.

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>@storybook/addon-essentials</b></summary>
    The new version differs by 250 commits.</br>
    <ul>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/49f18e828c3c543f1498ca57347c9f19b09fdc11">49f18e8</a> Bump version from &quot;8.0.0-rc.5&quot; to &quot;8.0.0&quot; [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/6c30c31e857ec347598f9e48d15c752f7047601a">6c30c31</a> Trigger release of 8.0.0 with empty commit</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/8c7c2968494c9742cb1e82e5b6421a927b57e7b6">8c7c296</a> Write changelog [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/82e153f4648f7b68254d453cde4d360e13f3f6e4">82e153f</a> Merge pull request #26358 from storybookjs/framework-doc-svelte-vite</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/fffbbc9db03f9fc4fd1de7c26725f42c779e7f69">fffbbc9</a> Add &#x60;svelte-vite&#x60; framework doc</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/298d60ce9297f169c1587ab06984d2b6b37b7dbf">298d60c</a> Merge pull request #26265 from storybookjs/framework-doc-react-webpack5</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/f9646ddf049d5bfb0a709dd1ce733b6f17dcc357">f9646dd</a> Address comments</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/d392a9077658200e17151911224081b8eefa628a">d392a90</a> Add &#x60;react-webpack5&#x60; framework doc</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/3004edfbf3cae4a814e7dfff3d99c44062ce7e98">3004edf</a> Merge pull request #26264 from storybookjs/framework-doc-react-vite</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/3586fc9b27833b275c7296cf7f38ae48a3ae1e35">3586fc9</a> Address comments</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/116fd4acd4a86e49d528644e6a375e2984da4007">116fd4a</a> Add react-vite framework doc</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/9050c69a50e5eb042a4a43b8007ee7ce5cb39c63">9050c69</a> Bump version from &quot;8.0.0-rc.4&quot; to &quot;8.0.0-rc.5&quot; [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/1e33053988e7aaa0f917ef8513926696ccc4b9b8">1e33053</a> Merge pull request #26412 from storybookjs/version-non-patch-from-8.0.0-rc.4</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/cdfd820763709497df94b06aae72d33aeca140be">cdfd820</a> Write changelog for 8.0.0-rc.5 [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/eac3a3bc5a40b1dd7482543409ad440b23e8efc0">eac3a3b</a> Merge pull request #26410 from storybookjs/norbert/fix-automigration-latest-detection</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/d978771b182d2a98035fa650f91fa7b949ab2089">d978771</a> add a flag for detecting is the latest version we got from npm matches the version of the CLI exactly</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/bfa05701390eea3954e853de4208f18b6862cd68">bfa0570</a> Bump version from &quot;8.0.0-rc.3&quot; to &quot;8.0.0-rc.4&quot; [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/46bc788845877af65b76ba2719c4b04874e8388a">46bc788</a> Merge pull request #26370 from storybookjs/version-non-patch-from-8.0.0-rc.3</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/a6e4d90993a1a027edd26536091a5751c34d1e94">a6e4d90</a> Write changelog for 8.0.0-rc.4 [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/37276b295395cc1e343f60b6db83e5689019df09">37276b2</a> Merge pull request #26321 from storybookjs/docs_snapshot_testing</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/c1fc1912b72e7d7100165d3738e09b99569d0736">c1fc191</a> Merge branch &#x27;next&#x27; into docs_snapshot_testing</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/4f6f0445fc40be1cca5f2c44cd2bfce3c5bee183">4f6f044</a> Merge pull request #26405 from storybookjs/norbert/fix-esbuild-version</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/9c2d525b5483bd71da3ddca15dd265ce8d14e9f3">9c2d525</a> fix the esbuild compatibility versions ranges</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/973fa2d523becd760f62f0d29f3091ad10e12ac6">973fa2d</a> Merge pull request #26398 from storybookjs/docs_fix_tables</li>
    </ul>

   <a href="https://snyk.io/redirect/github/storybookjs/storybook/compare/287300bcde01caf7612225c4ef8c1d9b9f559f27...49f18e828c3c543f1498ca57347c9f19b09fdc11">See the full diff</a>
  </details>
  <details>
    <summary>Package name: <b>storybook</b></summary>
    The new version differs by 250 commits.</br>
    <ul>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/49f18e828c3c543f1498ca57347c9f19b09fdc11">49f18e8</a> Bump version from &quot;8.0.0-rc.5&quot; to &quot;8.0.0&quot; [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/6c30c31e857ec347598f9e48d15c752f7047601a">6c30c31</a> Trigger release of 8.0.0 with empty commit</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/8c7c2968494c9742cb1e82e5b6421a927b57e7b6">8c7c296</a> Write changelog [skip ci]</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/82e153f4648f7b68254d453cde4d360e13f3f6e4">82e153f</a> Merge pull request #26358 from storybookjs/framework-doc-svelte-vite</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/fffbbc9db03f9fc4fd1de7c26725f42c779e7f69">fffbbc9</a> Add &#x60;svelte-vite&#x60; framework doc</li>
      <li><a href="https://snyk.io/redirect/github/storybookjs/storybook/commit/298d60ce9297f169c1587ab06984d2b6b37b7dbf">298d60c</a> Merge pull request #26265 fro [...]

2024-03-12 15:34 UTC, fbosquet-azpn commented
@GuillaumeVix 
Please cancel this review, if you accept it as is it will break the build of storybook.
This is not the proper way to upgrade Storybook to newest version 8.

I am working on the side to properly migrate it using
'npx storybook@latest upgrade`
I am currently QC-ing the migration.

2024-03-14 08:41 UTC, t0oF-azpn requested changes
We probably want to migrate the whole storybook stack to v 8, not one by one.

2024-03-14 08:52 UTC, t0oF-azpn commented
> We probably want to migrate the whole storybook stack to v 8, not one by one.

Actually there will be a merge conflict with Fabien's work which already updated to storybook v 8.

BTW, is there any chance that I could be granted reviewer rights ?

2024-03-14 11:55 UTC, johannesleite commented
> BTW, is there any chance that I could be granted reviewer rights ?

I will bring it up @t0oF-azpn

2024-04-15 12:40 UTC, johannesleite commented
updated in https://github.com/equinor/videx-wellog/pull/235

2024-04-15 12:40 UTC, closed without merging